services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
       - .data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=SuperSecretPassword
      - POSTGRES_USER=terraspect_root
      - POSTGRES_DB=terraspect_db
